# 第4章：描述分析 {#ch4}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, cache = T)
```

```{r message=FALSE,warning=FALSE}
### 数据准备 ###
# 清空工作空间
rm(list = ls())
# 载入相关包及设定路径
library(plyr)
library(dplyr)
library(stringr)
library(tidyr)
library(corrplot)
library(ggplot2)
library(zoo)
library(reshape2)
library(plotly)
Sys.setlocale("LC_ALL", "zh_cn.utf-8")

# 读入数据
novel = read.csv('./data/novel.csv', fileEncoding = "UTF-8")
# 数据查看与异常处理
head(novel)
```


## 柱状图、直方图、饼图

### 柱状图

```{r, warning=FALSE}
# 统计小说类型频数
a=table(novel$小说类型)
# 对频数排序
a=a[order(a,decreasing = T)]
```

```{r nice-fig, fig.cap='test for plot online', out.width='80%', fig.asp=.75, fig.align='center'}
# 绘制柱状图
par(family = "SimSun",las = 2)
barplot(a[1:5],names.arg = names(a)[1:5],family="SimSun",ylab = "频数",xlab="",col = c("gold","grey","grey","grey","grey"))
title("各类型小说频数分布柱状图",family="SimSun")

```

```{r, warning=FALSE}
# 求得各类型小说平均点击数的均值
means<-novel%>%
  group_by(小说类型)%>%
  summarise(mean = mean(总点击数/10000))%>%
  arrange(desc(mean))
par(family = "SimSun",las = 2)
# 绘制均值柱状图
barplot(means$mean[1:5], names.arg=means$小说类型[1:5],family="SimSun",ylab = "总点击数(万次)",xlab="",col = c("gold","grey","grey","grey","grey"))
title("各类型小说平均总点击数",family="SimSun")

options(scipen = 200)

```

```{r, warning=FALSE}
# 构建绘图所需数据矩阵d
d = novel%>%group_by(小说类型,小说性质)%>%
  dplyr::summarise(count=n())%>%
  spread(小说性质,count)%>%
  select(-V1)%>%
  arrange(desc(公众作品))
topics = d$小说类型[1:5]
artwork_type = colnames(d)[2:3]
# 选取前五类小说
d = matrix(as.numeric(t(d[1:5,])[-1,]),nrow=2)
# 对列命名
colnames(d) = topics
# 对行命名
rownames(d) = artwork_type

# 绘制分组柱状图(beside = T)
par(mfrow=c(1,2), family = "SimSun",las=2)
barplot(d, beside = T, col = c("gold","grey"), ylab = "频数", ylim = c(0,500))
# 添加图例
legend("topright", legend = rownames(d), fill =  c("gold","grey"), cex = 0.8)
# 绘制堆积柱状图(beside = F)
barplot(d, beside = F, col = c("gold","grey"), ylab = "频数", ylim = c(0,700))
# 添加图例
legend("topright", legend = rownames(d), fill = c("gold", "grey"), cex = 0.8)
```

### 饼图

```{r}
# 将小说类型进行简要合并
novel$'小说类别' = "其他"
novel$'小说类别'[novel$小说类型 == "都市小说" | novel$小说类型 == "职场小说"] = "都市类小说"
novel$'小说类别'[novel$小说类型 == "科幻小说" | novel$小说类型 == "玄幻小说" | novel$小说类型 == "奇幻小说"] = "幻想类小说"
novel$'小说类别'[novel$小说类型 == "武侠小说" | novel$小说类型 == "仙侠小说"] = "武侠类小说"
# 求出每一类所占百分比
ratio = table(novel$'小说类别') / sum(table(novel$'小说类别')) * 100
# 定义标签
label1 = names(ratio)
label2 = paste0(round(ratio, 2), "%")
# 绘制饼图
par(family="SimSun") 
pie(ratio, col = heat.colors(5, alpha = 0.4), labels = paste(label1, label2, sep = "\n"), font = 1)
```

### 直方图

```{r eval=FALSE, include=FALSE}
# 随机生成1000个正态分布数
r=rnorm(1000)
# 绘制直方图
hist(r) 
```


```{r, warning=FALSE}
# 去掉异常值
chara = sort(novel$总字数/10000)[1:1500] 
# 绘制直方图
par(mfrow=c(1,2),family = "SimSun",las=2)
hist(chara, breaks = 10, xlab = "总字数(万字)", ylab = "频数", main = "", col = "gold",border = NA)
# 调整直方图组距
hist(chara, breaks = 100, xlab = "总字数(万字)", ylab = "频数", main = "", col = "gold",border = NA)
```

## 箱线图、饼图、散点图

### 折线图
```{r}
# 获取数据
data(AirPassengers)
# 画时间序列图
plot(AirPassengers)
```


### 箱线图
```{r}
## 定性与定量变量--分组箱线图 ##
# 将画板分成1行2列
par(mfrow=c(1,2),family = "SimSun")  
# 不同性质的小说总点击数和评论数有差别吗
novel_ = novel%>%filter(小说性质 == '公众作品'|小说性质 == 'VIP作品')%>%mutate(小说性质=factor(小说性质))
boxplot(log(总点击数) ~ 小说性质, data = novel_, col = c('gold','grey'), ylab = "总点击数对数")
boxplot(log(总点击数) ~ 小说性质, data = novel_, col = c('gold','grey'), ylab = "总评论数对数")



```

### 散点图
```{r}
## 两个定量变量--散点图 ##
# 去除较大的异常值后画图
test = novel[novel$评论数 < 8000 & novel$总点击数 < 200000, ]
x = test$总点击数
y = test$评论数
par(family = "SimSun")  
plot(x, y, pch = 1, cex = 0.6, xlab = "总点击数", ylab = "评论数")
```
