---
title: "统计分析（以R语言为工具）：辅助材料"
author: 
  - 朱雪宁 & 任怡萌
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output: bookdown::gitbook
github-repo: XueningZhu/Statistical-Analysis-with-R

# output:
#   bookdown::gitbook: default
  #bookdown::pdf_book: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, cache = T)
```

# 前言 {-}

这是《统计分析（以R语言为工具）》一书所用R语言代码辅助材料，还在更新中。错漏之处难免，欢迎指出错误或提出改进意见。

**相关下载**：

- [一些配套数据的打包文件](https://pan.baidu.com/s/11Ya1rBBFlhj1YO2uW_GToQ)，提取码：zi7w

本书所使用的课件：

- [第4章：数据描述与可视化](https://pan.baidu.com/s/1Mg4cNmuii_9RtMa2CW0WtA)，提取码：3h4g

- [第5章：参数估计与假设检验](https://pan.baidu.com/s/1ty69tzyUtINJDmmpYaNY9Q)，提取码：0smb

- [第6章：线性回归](https://pan.baidu.com/s/1lI_X8Wm4IReKtom-A5nTJQ)，提取码：iais

- [第7章：逻辑回归](https://pan.baidu.com/s/1vx_cLjEq7H_eYX4dTj1c3w)，提取码：4d67

- [第8章：降维分析](https://pan.baidu.com/s/1TpuHwd6ByUnlqql1KG90Vg)，提取码：lvkp

使用本教程必须安装的**软件包**：

- resahpe
- reshape2
- plyr
- dplyr
- readxl
- lubridate
- stringr
- e1071
- fBasics
- tidyr
- corrplot
- ggplot2
- zoo
- plotly
- purrr
- data.table
- magrittr
- BSDA
- pROC
- ROCR
- psych

本教程中用到的软件包列表（更新R软件后可以在一个基本R中运行如下命令）：

```{r echo = T, eval = F}
pkgs <- c("resahpe", "reshape2", "plyr", "dplyr", "readxl", "lubridate", 
          "stringr", "e1071", "fBasics", "tidyr", "corrplot", "ggplot2",
          "zoo", "plotly", "purrr", "data.table", "magrittr", "BSDA",
          "pROC", "ROCR", "psych")
install.packages(unique(pkgs))
```

编译本教程所用的R软件环境：

```{r}
devtools::session_info()
```
